<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $text
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['text'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Название',
            'text' => 'Текст',
        ];
    }

    public function getDomains()
    {
        return $this->hasMany(Domain::className(), ['category_id' => 'id']);
    }

    public function beforeDelete()
    {
        foreach ($this->domains as $domain) {
            $domain->delete();
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
